 files: 
  "/home/toni/workspace/linkma/test_output/.bashrc":
    contents:
      internal: "
        echo \"hi\""

  "/home/toni/workspace/linkma/test_output/fstab":
      contents:
        external: ./example/fstab
